DROP TABLE [dbo].[Product]
CREATE TABLE [dbo].[Product] (
    [ProductId]          INT            IDENTITY (1, 1) NOT NULL,
    [ProductNO]          VARCHAR (10)     NOT NULL,
    [ProductName]        VARCHAR (30)      NOT NULL,
    [ProductDescription] VARCHAR(100)     NOT NULL,
    [UnitPrice]          NUMERIC (7, 2) NOT NULL,
    [MainCategoryID]     INT            NOT NULL,
    [SubCategoryID]      INT            NOT NULL,
    [Productimg]         VARCHAR (50)   NULL,
    [Featured]           CHAR (1)       NULL,
    PRIMARY KEY CLUSTERED ([ProductId] ASC)
);
SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (1, N'HH00', N'Nancy Heel', N'Stylish High Heel', CAST(29.99 AS Decimal(7, 2)), 1, 5, N'~\img\product\heels\high\hh00.jpg', N'y')
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (3, N'HH01', N'Hailey Heel', N'Nice Heels', CAST(34.99 AS Decimal(7, 2)), 1, 5, N'~\img\product\heels\high\hh01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (4, N'HH02', N'Spiked Heel', N'These heels are spikey.', CAST(54.99 AS Decimal(7, 2)), 1, 5, N'~\img\product\heels\high\hh02.jpg', N'y')
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (6, N'HH03', N'Coco Heel', N'Tropical vibes.', CAST(80.99 AS Decimal(7, 2)), 1, 5, N'~\img\product\heels\high\hh03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (7, N'HS01', N'Nancy Shorty Heel', N'Sylish heels on the low end for the working person.', CAST(29.99 AS Decimal(7, 2)), 1, 6, N'~\img\product\heels\short\hs01.jpg', N'y')
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (8, N'HS02', N'Debby Toe', N'Cute peek a boo heels perfect for the office or a sunday brunch.', CAST(18.99 AS Decimal(7, 2)), 1, 6, N'~\img\product\heels\short\hs02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (13, N'HS03', N'Luxe lil Pump', N'Short pumps cute enough to pump up your mood', CAST(20.99 AS Decimal(7, 2)), 1, 6, N'~\img\product\heels\short\hs03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (15, N'HS04', N'Wittle Heel', N'Cute short heels', CAST(16.99 AS Decimal(7, 2)), 1, 6, N'~\img\product\heels\short\hs04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (16, N'HST1', N'Fasholettos', N'Comfortable Sexy and cute stilletoes of the future.', CAST(699.99 AS Decimal(7, 2)), 1, 7, N'~\img\product\heels\stilettos\hst1.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (18, N'HST2', N'Rippa Heels', N'Rip through the room in these stilletoes, made to make a statement', CAST(29.99 AS Decimal(7, 2)), 1, 7, N'~\img\product\heels\stilettos\hst2.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (19, N'HST3', N'Rina GoGo', N'Go Go stilettos not in boot form.', CAST(30.99 AS Decimal(7, 2)), 1, 7, N'~\img\product\heels\stilettos\hst3.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (21, N'HST4', N'Spikelettos', N'Spiked Stilettos', CAST(49.99 AS Decimal(7, 2)), 1, 7, N'~\img\product\heels\stilettos\hst4.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (22, N'HP01', N'Nancy Platform Heel', N'Stylish Platform Heels from the Nacy collection', CAST(24.99 AS Decimal(7, 2)), 1, 8, N'~\img\product\heels\platform\hp01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (23, N'HP02', N'Hailey Platform Heel', N'Nice Platform Heels', CAST(30.99 AS Decimal(7, 2)), 1, 8, N'~\img\product\heels\platform\hp02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (24, N'HP03', N'Spikey Platform Heels', N'Awesome Platform heels for the mosh pit.', CAST(49.99 AS Decimal(7, 2)), 1, 8, N'~\img\product\heels\platform\hp03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (27, N'HP04', N'Jeffrey Campbell''s Barbie', N'IKES. AWESOME. YOU KIND WANT THEM YEAH?', CAST(129.99 AS Decimal(7, 2)), 1, 8, N'~\img\product\heels\platform\hp04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (28, N'FS01', N'Nike Flynit', N'Tennis shoes with rain deffering technology. Will not need replacement after 1 year of use', CAST(80.99 AS Decimal(7, 2)), 1, 10, N'~\img\product\flats\sneakers\fs01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (29, N'FS02', N'Adidas Boost', N'Comfortable technological tennis shoes, streetware.', CAST(94.99 AS Decimal(7, 2)), 1, 10, N'~\img\product\flats\sneakers\fs02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (30, N'FS03', N'Fila Run Run', N'Comfortable work out shoe with water repelling technology', CAST(19.99 AS Decimal(7, 2)), 1, 10, N'~\img\product\flats\sneakers\fs03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (31, N'FS04', N'Air Jordan', N'The best shoe.', CAST(699.00 AS Decimal(7, 2)), 1, 10, N'~\img\product\flats\sneakers\fs04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (33, N'FB01', N'Ballet Twinky', N'Cute ballet flat', CAST(20.99 AS Decimal(7, 2)), 1, 11, N'~\img\product\flats\ballet\fb01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (35, N'FB02', N'Ponylet Flats', N'Comfotable Ballet flats', CAST(21.99 AS Decimal(7, 2)), 1, 11, N'~\img\product\flats\ballet\fb02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (40, N'FB03', N'Nike Dance', N'flats, streetware, made for dance room. Water repelling technonogy, etra slip and extra grip', CAST(30.99 AS Decimal(7, 2)), 1, 11, N'~\img\product\flats\ballet\fb03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (41, N'FB04', N'Faux Suede Ankle Strap', N'Cute no fly off ballet flat', CAST(19.99 AS Decimal(7, 2)), 1, 11, N'~\img\product\flats\ballet\fb04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (42, N'FE01', N'Rise Beach Flat', N'perfect to get sand in', CAST(16.99 AS Decimal(7, 2)), 1, 12, N'~\img\product\flats\espadrilles\fe01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (43, N'FE02', N'Blue Cool Flat', N'Beach no bummer with these shows', CAST(14.99 AS Decimal(7, 2)), 1, 12, N'~\img\product\flats\espadrilles\fe02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (45, N'FE03', N'London Rebel Tie Flat', N'Tie up and head out in these cuties', CAST(19.99 AS Decimal(7, 2)), 1, 12, N'~\img\product\flats\espadrilles\fe03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (46, N'FE04', N'Nancy Cool Flats', N'Stylish beach vibe flats', CAST(17.99 AS Decimal(7, 2)), 1, 12, N'~\img\product\flats\espadrilles\fe04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (48, N'FC01', N'Hailey Classic Flats', N'Cute classic nancy flat', CAST(12.99 AS Decimal(7, 2)), 1, 13, N'~\img\product\flats\classic\fc01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (50, N'FC02', N'Nancy Classic Flat', N'stylish classic flat from ancy collection', CAST(13.99 AS Decimal(7, 2)), 1, 13, N'~\img\product\flats\classic\fc02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (51, N'FC03', N'Fashola Classic Flat', N'Perfect flat for a formal occasion. Look classic and feel it.', CAST(50.99 AS Decimal(7, 2)), 1, 13, N'~\img\product\flats\classic\fc03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (52, N'FC04', N'Debby Flat', N'Flats for the girls', CAST(15.99 AS Decimal(7, 2)), 1, 13, N'~\img\product\flats\classic\fc04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (53, N'BR01', N'Nancy Rain Boot', N'boots for the rain', CAST(16.99 AS Decimal(7, 2)), 1, 14, N'~\img\product\boots\rain\br01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (54, N'BR02', N'Debby Rain Boots', N'boots for real rain', CAST(17.99 AS Decimal(7, 2)), 1, 14, N'~\img\product\boots\rain\br02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (55, N'BR03', N'Hailey Rain Boots', N'Chiq rain boots', CAST(18.99 AS Decimal(7, 2)), 1, 14, N'~\img\product\boots\rain\br03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (57, N'BR04', N'UGG Rain Boots', N'Gray Boots over starbucks', CAST(70.99 AS Decimal(7, 2)), 1, 14, N'~\img\product\boots\rain\br04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (58, N'BH01', N'Nancy booties', N'Nice booties', CAST(19.99 AS Decimal(7, 2)), 1, 15, N'~\img\product\boots\heeled\bh01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (59, N'BH02', N'Hailey Booties', N'Stylish booties', CAST(19.99 AS Decimal(7, 2)), 1, 15, N'~\img\product\boots\heeled\bh02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (60, N'BH03', N'Debby Booties', N'Comfortable booties', CAST(21.99 AS Decimal(7, 2)), 1, 15, N'~\img\product\boots\heeled\bh03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (62, N'BH04', N'Comebat Booties', N'Big Booties', CAST(34.99 AS Decimal(7, 2)), 1, 15, N'~\img\product\boots\heeled\bh04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (63, N'BT01', N'Nancy Thigh Highs', N'Thigh High boots make you look good', CAST(24.99 AS Decimal(7, 2)), 1, 16, N'~\img\product\boots\thigh\bt01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (64, N'BT02', N'Debby Black Thigh', N'Thigh High Boots from the debby collection.', CAST(29.99 AS Decimal(7, 2)), 1, 16, N'~\img\product\boots\thigh\bt02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (65, N'BT03', N'Fashola Thigh Highs', N'Clear beautiful thigh high boots for any weather.', CAST(199.99 AS Decimal(7, 2)), 1, 16, N'~\img\product\boots\thigh\bt03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (66, N'BT04', N'Hailey BDSN', N'Red Thigh High Boots', CAST(45.99 AS Decimal(7, 2)), 1, 16, N'~\img\product\boots\thigh\bt04.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (67, N'BC01', N'Nancy Combat', N'Ready for combat with nancy, nice boots.', CAST(29.99 AS Decimal(7, 2)), 1, 17, N'~\img\product\boots\combat\bc01.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (68, N'BC02', N'Hailey Combat Me Boots', N'Cute Combat Boots', CAST(25.99 AS Decimal(7, 2)), 1, 17, N'~\img\product\boots\combat\bc02.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (69, N'BC03', N'Debby Combat Boots', N'Stylish Combat Boots', CAST(30.99 AS Decimal(7, 2)), 1, 17, N'~\img\product\boots\combat\bc03.jpg', NULL)
INSERT INTO [dbo].[Product] ([ProductId], [ProductNO], [ProductName], [ProductDescription], [UnitPrice], [MainCategoryID], [SubCategoryID], [Productimg], [Featured]) VALUES (71, N'BC04', N'Prada Zip Up Combat Boots', N'It''s prada. Leather zip up combat boots.', CAST(1350.00 AS Decimal(7, 2)), 1, 17, N'~\img\product\boots\combat\bc04.jpg', NULL)
SET IDENTITY_INSERT [dbo].[Product] OFF


